[package]
name = "image-file-format"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
minifb = "0.27"
piston_window = "0.132.0"
glium = "0.36.0"

[workspace]
exclude = ["output.quiche"]